// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Stock implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stockMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Stock";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		Name("Name"),
		Abbr("Abbr"),
		Value("Value"),
		Profit("Profit"),
		Stock_Root("MyFirstModule.Stock_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Stock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Stock(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stockMendixObject)
	{
		if (stockMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, stockMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.stockMendixObject = stockMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Stock initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Stock(context, mendixObject);
	}

	public static myfirstmodule.proxies.Stock load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Stock.initialize(context, mendixObject);
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.Integer get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.Integer get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.Integer _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Abbr
	 */
	public final java.lang.String getAbbr()
	{
		return getAbbr(getContext());
	}

	/**
	 * @param context
	 * @return value of Abbr
	 */
	public final java.lang.String getAbbr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Abbr.toString());
	}

	/**
	 * Set value of Abbr
	 * @param abbr
	 */
	public final void setAbbr(java.lang.String abbr)
	{
		setAbbr(getContext(), abbr);
	}

	/**
	 * Set value of Abbr
	 * @param context
	 * @param abbr
	 */
	public final void setAbbr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String abbr)
	{
		getMendixObject().setValue(context, MemberNames.Abbr.toString(), abbr);
	}

	/**
	 * @return value of Value
	 */
	public final java.math.BigDecimal getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.math.BigDecimal getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.math.BigDecimal value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @return value of Profit
	 */
	public final java.lang.Boolean getProfit()
	{
		return getProfit(getContext());
	}

	/**
	 * @param context
	 * @return value of Profit
	 */
	public final java.lang.Boolean getProfit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Profit.toString());
	}

	/**
	 * Set value of Profit
	 * @param profit
	 */
	public final void setProfit(java.lang.Boolean profit)
	{
		setProfit(getContext(), profit);
	}

	/**
	 * Set value of Profit
	 * @param context
	 * @param profit
	 */
	public final void setProfit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean profit)
	{
		getMendixObject().setValue(context, MemberNames.Profit.toString(), profit);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Stock_Root
	 */
	public final myfirstmodule.proxies.Root getStock_Root() throws com.mendix.core.CoreException
	{
		return getStock_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Stock_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Root getStock_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Stock_Root.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Stock_Root
	 * @param stock_root
	 */
	public final void setStock_Root(myfirstmodule.proxies.Root stock_root)
	{
		setStock_Root(getContext(), stock_root);
	}

	/**
	 * Set value of Stock_Root
	 * @param context
	 * @param stock_root
	 */
	public final void setStock_Root(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Root stock_root)
	{
		if (stock_root == null) {
			getMendixObject().setValue(context, MemberNames.Stock_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Stock_Root.toString(), stock_root.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stockMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Stock that = (myfirstmodule.proxies.Stock) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
